-- MySQL Script generated by MySQL Workbench
-- Thu Nov 25 18:58:14 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`log` ;

CREATE TABLE IF NOT EXISTS `mydb`.`log` (
  `usuarios_id` VARCHAR(45) NOT NULL,
  `entrada` DATETIME NOT NULL,
  `salida` DATETIME NOT NULL,
  PRIMARY KEY (`usuarios_id`),
  CONSTRAINT `fk_log_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`oficinas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`oficinas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`oficinas` (
  `id_oficina` INT NOT NULL,
  `aforo` INT NOT NULL,
  PRIMARY KEY (`id_oficina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rfid`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`rfid` ;

CREATE TABLE IF NOT EXISTS `mydb`.`rfid` (
  `id_rfid` VARCHAR(10) NOT NULL,
  `usuarios_id` VARCHAR(45) NOT NULL,
  `oficinas_id` INT NOT NULL,
  PRIMARY KEY (`id_rfid`),
  INDEX `fk_rfid_usuarios1_idx` (`usuarios_id` ASC) VISIBLE,
  INDEX `fk_rfid_oficinas1_idx` (`oficinas_id` ASC) VISIBLE,
  CONSTRAINT `fk_rfid_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rfid_oficinas1`
    FOREIGN KEY (`oficinas_id`)
    REFERENCES `mydb`.`oficinas` (`id_oficina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`table1` ;

CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(60) NOT NULL,
  `DNI` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(9) NOT NULL,
  `Nombre Completo` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
