-- MySQL Script generated by MySQL Workbench
-- Fri Dec 24 01:13:57 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema controlaforo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `controlaforo` ;

-- -----------------------------------------------------
-- Schema controlaforo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `controlaforo` DEFAULT CHARACTER SET utf8 ;
USE `controlaforo` ;

-- -----------------------------------------------------
-- Table `controlaforo`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlaforo`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `controlaforo`.`usuarios` (
  `id_usuario` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(60) NOT NULL,
  `dni` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(9) NOT NULL,
  `nombre_completo` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlaforo`.`oficinas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlaforo`.`oficinas` ;

CREATE TABLE IF NOT EXISTS `controlaforo`.`oficinas` (
  `id_oficina` INT NOT NULL,
  `aforo` INT NOT NULL,
  PRIMARY KEY (`id_oficina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlaforo`.`rfid`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlaforo`.`rfid` ;

CREATE TABLE IF NOT EXISTS `controlaforo`.`rfid` (
  `id_rfid` VARCHAR(13) NOT NULL,
  `id_usuario` VARCHAR(45) NOT NULL,
  `id_oficina` INT NOT NULL,
  PRIMARY KEY (`id_rfid`),
  INDEX `fk_rfid_usuarios_idx` (`id_usuario` ASC),
  INDEX `fk_rfid_oficinas1_idx` (`id_oficina` ASC),
  CONSTRAINT `fk_rfid_usuarios`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `controlaforo`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_rfid_oficinas1`
    FOREIGN KEY (`id_oficina`)
    REFERENCES `controlaforo`.`oficinas` (`id_oficina`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlaforo`.`log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlaforo`.`log` ;

CREATE TABLE IF NOT EXISTS `controlaforo`.`log` (
  `id_usuario` VARCHAR(45) NOT NULL,
  `entrada` DATETIME NOT NULL,
  `salida` DATETIME NULL,
  PRIMARY KEY (`id_usuario`, `entrada`),
  CONSTRAINT `fk_log_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `controlaforo`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlaforo`.`positivos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlaforo`.`positivos` ;

CREATE TABLE IF NOT EXISTS `controlaforo`.`positivos` (
  `id_positivo` VARCHAR(45) NOT NULL,
  `fecha_positivo` DATETIME NOT NULL,
  `id_usuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_positivo`),
  INDEX `fk_positivos_usuarios1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_positivos_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `controlaforo`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `controlaforo`.`notificaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `controlaforo`.`notificaciones` ;

CREATE TABLE IF NOT EXISTS `controlaforo`.`notificaciones` (
  `id_notificacion` VARCHAR(45) NOT NULL,
  `id_usuario` VARCHAR(45) NOT NULL,
  `id_positivo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_notificacion`),
  INDEX `fk_notificaciones_usuarios1_idx` (`id_usuario` ASC),
  INDEX `fk_notificaciones_positivos1_idx` (`id_positivo` ASC),
  CONSTRAINT `fk_notificaciones_usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `controlaforo`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_notificaciones_positivos1`
    FOREIGN KEY (`id_positivo`)
    REFERENCES `controlaforo`.`positivos` (`id_positivo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
